import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import HeaderRepository from "./lib/Header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const headerData = await HeaderRepository.getInstance().getModels();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Header
            data={headerData}
          />
        <main>{children}</main>
        <Footer data={headerData} />
      </body>
    </html>
  );
}
