import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Header from "./components/Header";
import HeaderRepository from "./lib/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

 const headerData = await HeaderRepository.getInstance().getModels();

 console.log("Header Layout data:", headerData);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header style={{ backgroundColor: "var(--primary)" }}>
          <Header data={headerData} />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
